---
- name: jtimon | create systemd service unit
  template:
    src: jtimon.service.j2
    dest: /etc/systemd/system/jtimon.service
    owner: root
    group: root
    mode: 0644
  notify: restart jtimon

- name: start and enable jtimon
  become: true
  systemd:
    name: "{{ jtimon_servicename }}"
    state: started
    enabled: yes

- name: jtimon | create config directory
  file:
    path: "{{ jtimon_etc }}"
    state: directory
    owner: "{{ jtimon_user }}"
    group: "{{ jtimon_user }}"
    mode: 0755

- name: jtimon | configure jtimon aliases
  template:
    src: jtimon-aliases.txt.j2
    dest: "{{ jtimon_alias_file }}"
    owner: "{{ jtimon_user }}"
    group: "{{ jtimon_user }}"
    mode: 0644
  notify: restart jtimon

- name: jtimon | configure jtimon main
  template:
    src: jtimon.json.j2
    dest: "{{ jtimon_etc }}/jtimon.json"
    owner: "{{ jtimon_user }}"
    group: "{{ jtimon_user }}"
    mode: 0644
  notify: restart jtimon

- name: jtimon | configure jtimon hosts
  template:
    src: jtimon-host.json.j2
    dest: "{{ jtimon_etc }}/config-{{item.host}}.json"
    owner: "{{ jtimon_user }}"
    group: "{{ jtimon_user }}"
    mode: 0644
  loop: "{{ jtimon_config_hosts }}"
  when: jtimon_config_hosts | length > 0
  notify: restart jtimon