---
- include: preflight.yml
  tags:
    - jtimon_install
    - jtimon_configure
    - jtimon_run

- include: install.yml
  become: true
  tags:
    - jtimon_install

- include: configure.yml
  become: true
  tags:
    - jtimon_configure